### ISSUE TITLE
Support passing additional headers to proxy as options

### ISSUE THREAD

**Issue by suzana-zevri** [edorivai/koa-proxy#10]
The `proxy` options object supports only suppressing headers, but there are situations when new headers are needed.

example:

```
const options = {
  url: CUSTOM_URL, 
  match: MATCH_PATTERN
  headers: {
    CUSTOM_HEADER_KEY: CUSTOM_HEADER_VALUE
  }
};
app.use(proxy(options));
```

These headers can be merged with the `ctx.request.header`

**Comment by suzana-zevri** [comment]
I just discovered that I can use `requestOptions` to achieve this, so closing this.
Might be worth adding examples to the documentation :)

**Comment by axolo** [comment]
```js
proxy({
  path: /^\/proxy-path/,
  host: 'HOST',
  requestOptions: {
    headers: {
      Authorization: 'Bearer TOKEN',
      'Content-Type': 'application/json'
    }
  }
})
```
